import type { AgentPlatID, JsonObject, JsonValue } from '@agentplat/core';
import {
  DefaultAgentRuntime,
  type AgentCompletionPayload,
  type AgentDefinition,
  type AgentProvider,
  type AgentRunInput,
  type AgentRunResult,
  type AgentStreamEvent,
  type RuntimeExecutionContext,
} from '@agentplat/runtime';

/** A scripted response consumed by one mock invocation. */
export interface MockAgentResponse {
  output: string;
  status?: 'completed' | 'failed';
  result?: JsonObject;
  errorMessage?: string;
  metadata?: JsonObject;
  /** Optional normalized details emitted on the completed stream event. */
  completion?: AgentCompletionPayload;
}

/** Deterministic behavior configured for a `MockAgentProvider` instance. */
export interface MockAgentProviderOptions {
  outputPrefix?: string;
  /** Responses are consumed in order; the final response is reused afterwards. */
  responses?: Array<string | MockAgentResponse>;
  /** Per-agent response tapes with independent invocation counters. */
  responsesByAgent?: Record<AgentPlatID, Array<string | MockAgentResponse>>;
  /** Exact stream events, useful for deterministic UI and transport tests. */
  streamEvents?: AgentStreamEvent[];
  /** Per-agent stream event tapes, indexed first by agent and then invocation. */
  streamEventsByAgent?: Record<AgentPlatID, AgentStreamEvent[][]>;
  /** Token chunks used when streamEvents is not provided. */
  streamTokens?: string[];
  tokenDelayMs?: number;
  /** One-based invocation number that should fail deterministically. */
  failAtCall?: number;
  artifactFactory?: (input: AgentRunInput) => {
    type?: string;
    title?: string;
    content: JsonValue;
    contentType?: string;
    assumptions?: string[];
    risks?: string[];
  };
}

/**
 * Network-free agent provider for examples, UI development and repeatable tests.
 *
 * A provider instance owns its invocation counter. Create a fresh instance in
 * each isolated test when response order matters.
 */
export class MockAgentProvider implements AgentProvider {
  private invocation = 0;
  private readonly invocationsByAgent = new Map<AgentPlatID, number>();

  constructor(private readonly options: MockAgentProviderOptions = {}) {
    if (
      options.tokenDelayMs !== undefined &&
      (!Number.isInteger(options.tokenDelayMs) || options.tokenDelayMs < 0)
    ) {
      throw new TypeError('tokenDelayMs must be a non-negative integer');
    }
    if (
      options.failAtCall !== undefined &&
      (!Number.isInteger(options.failAtCall) || options.failAtCall < 1)
    ) {
      throw new TypeError('failAtCall must be a positive integer');
    }
  }

  async run(
    agent: Parameters<AgentProvider['run']>[0],
    input: AgentRunInput,
    executionContext: Parameters<AgentProvider['run']>[2]
  ): Promise<AgentRunResult> {
    this.assertActive(executionContext.signal);
    const call = ++this.invocation;
    const agentCall = this.nextAgentCall(agent.id);
    await this.delay(executionContext.signal);
    if (this.options.failAtCall === call) {
      return {
        runId: executionContext.runId,
        status: 'failed',
        errorMessage: `Mock failure at call ${call}`,
        metadata: {
          provider: 'mock',
          deterministic: true,
          call,
          agentCall,
        },
      };
    }
    const scripted = this.scriptedResponse(agent.id, agentCall, call);
    if (scripted) {
      return {
        runId: executionContext.runId,
        status: scripted.status ?? 'completed',
        output: scripted.output,
        result: scripted.result,
        errorMessage: scripted.errorMessage,
        metadata: {
          ...(scripted.metadata ?? {}),
          provider: 'mock',
          deterministic: true,
          call,
          agentCall,
        },
      };
    }
    const expectedKind =
      typeof input.metadata?.expectedArtifactKind === 'string'
        ? input.metadata.expectedArtifactKind
        : 'document';
    const context = Array.isArray(input.input) ? input.input[0] : undefined;
    const instruction = this.readInstruction(context) ?? String(input.input);
    const produced = this.options.artifactFactory?.(input) ?? {
      type: expectedKind,
      title: `Mock ${expectedKind}`,
      content: `${this.options.outputPrefix ?? 'Mock output'}: ${instruction}`,
      contentType: 'text/plain',
      assumptions: ['Generated by the deterministic mock runtime'],
      risks: [],
    };
    const artifact: JsonObject = {
      type: produced.type ?? expectedKind,
      title: produced.title ?? `Mock ${expectedKind}`,
      content: produced.content,
      contentType: produced.contentType ?? 'application/json',
      assumptions: produced.assumptions ?? [],
      risks: produced.risks ?? [],
    };
    return {
      runId: executionContext.runId,
      status: 'completed',
      output:
        typeof produced.content === 'string'
          ? produced.content
          : JSON.stringify(produced.content),
      result: { artifact },
      metadata: {
        provider: 'mock',
        deterministic: true,
        call,
        agentCall,
      },
    };
  }

  async *stream(
    _agent: AgentDefinition,
    input: AgentRunInput,
    executionContext: RuntimeExecutionContext
  ): AsyncIterable<AgentStreamEvent> {
    this.assertActive(executionContext.signal);
    const call = ++this.invocation;
    const agentCall = this.nextAgentCall(_agent.id);
    const exactEvents =
      this.scriptedStreamEvents(_agent.id, agentCall) ??
      this.options.streamEvents;
    if (exactEvents) {
      for (const event of exactEvents) {
        await this.delay(executionContext.signal);
        yield {
          ...event,
          runId: event.runId ?? executionContext.runId,
        };
      }
      return;
    }

    yield { type: 'started', runId: executionContext.runId };
    if (this.options.failAtCall === call) {
      yield {
        type: 'failed',
        runId: executionContext.runId,
        content: `Mock failure at call ${call}`,
      };
      return;
    }
    const scripted = this.scriptedResponse(_agent.id, agentCall, call);
    const output =
      scripted?.output ??
      `${this.options.outputPrefix ?? 'Mock output'}: ${
        this.readInstruction(
          Array.isArray(input.input) ? input.input[0] : undefined
        ) ?? String(input.input)
      }`;
    const tokens = this.options.streamTokens ?? tokenize(output);
    for (const token of tokens) {
      await this.delay(executionContext.signal);
      yield {
        type: 'token',
        runId: executionContext.runId,
        content: token,
      };
    }
    if (scripted?.status === 'failed') {
      yield {
        type: 'failed',
        runId: executionContext.runId,
        content: scripted.errorMessage ?? scripted.output,
      };
      return;
    }
    yield {
      type: 'completed',
      runId: executionContext.runId,
      content: output,
      payload: scripted?.completion,
    };
  }

  private readInstruction(context: JsonObject | undefined): string | undefined {
    const task = context?.task;
    if (!task || typeof task !== 'object' || Array.isArray(task))
      return undefined;
    return typeof task.instruction === 'string' ? task.instruction : undefined;
  }

  private scriptedResponse(
    agentId: AgentPlatID,
    agentCall: number,
    globalCall: number
  ): MockAgentResponse | undefined {
    const agentResponses = this.options.responsesByAgent?.[agentId];
    if (agentResponses?.length) {
      return selectedResponse(agentResponses, agentCall);
    }
    const responses = this.options.responses;
    if (!responses?.length) return undefined;
    return selectedResponse(responses, globalCall);
  }

  private scriptedStreamEvents(
    agentId: AgentPlatID,
    agentCall: number
  ): AgentStreamEvent[] | undefined {
    const invocations = this.options.streamEventsByAgent?.[agentId];
    if (!invocations?.length) return undefined;
    return invocations[Math.min(agentCall - 1, invocations.length - 1)];
  }

  private nextAgentCall(agentId: AgentPlatID): number {
    const call = (this.invocationsByAgent.get(agentId) ?? 0) + 1;
    this.invocationsByAgent.set(agentId, call);
    return call;
  }

  private assertActive(signal: AbortSignal | undefined): void {
    if (signal?.aborted) {
      throw signal.reason ?? new Error('Mock runtime aborted');
    }
  }

  private async delay(signal: AbortSignal | undefined): Promise<void> {
    this.assertActive(signal);
    const delay = this.options.tokenDelayMs ?? 0;
    if (delay === 0) return;
    await new Promise<void>((resolve, reject) => {
      const onAbort = () => {
        clearTimeout(timeout);
        reject(signal?.reason ?? new Error('Mock runtime aborted'));
      };
      const timeout = setTimeout(() => {
        signal?.removeEventListener('abort', onAbort);
        resolve();
      }, delay);
      signal?.addEventListener('abort', onAbort, { once: true });
    });
  }
}

function selectedResponse(
  responses: Array<string | MockAgentResponse>,
  call: number
): MockAgentResponse {
  const selected = responses[Math.min(call - 1, responses.length - 1)];
  return typeof selected === 'string' ? { output: selected } : selected;
}

function tokenize(output: string): string[] {
  return output.match(/\S+\s*/g) ?? (output ? [output] : []);
}

/** Create a runtime with one deterministic provider registered as `mock`. */
export function createMockRuntime(
  options: MockAgentProviderOptions = {}
): DefaultAgentRuntime {
  const runtime = new DefaultAgentRuntime();
  runtime.registerProvider('mock', new MockAgentProvider(options));
  return runtime;
}
